export const UPDATE_TABLE_VALUES = "UPDATE_TABLE_VALUES";
export const UPDATE_TABLE_test = "UPDATE_TABLE_test";
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
export const FETCH_FILTER_VALUES = 'FETCH_FILTER_VALUES'